### PR TITLE
(GH-8) Set correct path to node

### LINKED ISSUE #8: Invalid path to node
Path to node is incorrect and gives the following error:

```sh
1. Determining matching Azure Pipelines agent...
2. Downloading and installing Azure Pipelines agent...
3. Configuring Azure Pipelines agent...

>> End User License Agreements:

Building sources from a TFVC repository requires accepting the Team Explorer Everywhere End User License Agreement. This step is not required for building sources from Git repositories.

A copy of the Team Explorer Everywhere license agreement can be found at:
   /azp/agent/externals/tee/license.html


>> Connect:

Connecting to server ...

>> Register Agent:

Scanning for tool capabilities.
Connecting to the server.
Successfully replaced the agent
Testing agent connection.
2019-05-29 06:46:27Z: Settings Saved.
4. Running Azure Pipelines agent...
/usr/local/bin/docker-entrypoint.sh: line 92: /azp/agent/externals/node10/bin/node: No such file or directory
```

### PR DESCRIPTION
**Pull request by jokay**
Sets the correct path to `node`.

Fixes #8.

### CODE REVIEW

File: docker-entrypoint.sh [hunk 1]
```diff
@@ -89,4 +89,5 @@ print_header "4. Running Azure Pipelines agent..."
 
 # `exec` the node runtime so it's aware of TERM and INT signals
 # AgentService.js understands how to handle agent self-update and restart
-exec ./externals/node10/bin/node ./bin/AgentService.js interactive
\ No newline at end of file
+#exec ./externals/node10/bin/node ./bin/AgentService.js interactive
```
Comment (pascalberger) [inline docker-entrypoint.sh]: Remove commented out line

**Review by pascalberger — CHANGES_REQUESTED** [review]
Please also add an issue or PR to [upstream documentation](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops#create-and-build-the-dockerfile)

**Comment by jokay** [comment]
Created [PR 4370](https://github.com/MicrosoftDocs/vsts-docs/pull/4370) for the docu.

**Review by pascalberger — APPROVED** [review]
